export { default as GatsbyLogo } from './GatsbyLogo'
export { default as TailwindLogo } from './TailwindLogo'
export { default as JsLogo } from './JsLogo'
export { default as Ellipses } from './Ellipses'
export { default as VerifyLogo } from './VerifyLogo'
export { default as PharmacareLogo } from './PharmacareLogo'
